### ISSUE TITLE
rotate not working

### ISSUE THREAD

**Issue by SearchAndDestroy** [baikalminer/multi-algo-miner#1]
I added rotate:120 to the options so the miner switches pools every 120 minutes but it it not switching at all.
It's activated and visible when I check the mining process directly (via the screen session) 
I also tried load-balance:true and this is working and it's mining on all the pools.
I emailed support about it on Feb 3 but got no reply. All I got was multi-algo switching works only on NiceHash.
I don't want to switch algo,, I want to alternate mining on 2 pools every X days.
Thanks for looking into that bug.

**Comment by SearchAndDestroy** [comment]
From the sgminer github:
https://github.com/sgminer-dev/sgminer/blob/master/doc/configuration.md
`rotate

Changes the multipool strategy to rotate between pools after a certain amount of time in seconds.

Available: Global

Config File Syntax: "rotate":"<value>"

Command Line Syntax: --rotate <value>

Argument: number Number of seconds between 0 and 9999 before switching to the next pool

Default: None`

**Comment by baikalminer** [comment]
Dear Sir / Madam.

First, I am very sorry for late reply.

Please update your miner with  recent oragenPI Image.

It has sgminer-5.x and it supports rotate function.

Thank you.



2017-06-27 3:19 GMT+09:00 Toresh <notifications@github.com>:

**Comment by SearchAndDestroy** [comment]
Thank you :)
I'll update asap and retry.
I have a mini[v2.1], so the image I use is the OrangePi One, correct?

**Comment by baikalminer** [comment]
Right, You just update the sdcard with OrangePI One.

2017-06-27 20:56 GMT+09:00 Toresh <notifications@github.com>:

**Comment by SearchAndDestroy** [comment]
Updated and il looks like it's rotating properly,
Thanks.
